# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.TextField(default='', max_length=10),
        ),
    ]
