# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160404_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
