# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_song_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'p2s',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareable', models.BooleanField(default=False)),
                ('name', models.TextField(default='Private Playlist')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Member')),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.AddField(
            model_name='p2s',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Playlist'),
        ),
        migrations.AddField(
            model_name='p2s',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Song'),
        ),
    ]
