# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_playlist_clone_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='users_rated',
            field=models.IntegerField(default=0),
        ),
    ]
